# pnpm-workspace.yaml
packages:
  # All packages in subdirs of packages/
  - "packages/*"
  # Specifically include a project in the root sub-folder
  - "!**/test/**"
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
